version: '3'

services:
  api:
    restart: always
    build: ./api
    ports:
      - 5555:5000
    depends_on:
      - mysql
  frontend:
    restart: always
    build: ./frontend
    ports:
      - 8954:8954
  mysql:
    restart: always
    image: mysql
    environment:
      - MY_SQL_ROOT_PASSWORD=password
      - MY_SQL_DATABASE=time_db
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    restart: always
    image: adminer
    ports:
      - 8080:8080
volumes:
  mysql_data: